# Providers
providers = ["python", "node"]

[phases.setup]
nixPkgs = ["python311", "nodejs_20"]

[phases.install]
dependsOn = ["setup"]
cmds = [
    "npm install --prefix ksl-web"
]

[phases.build]
dependsOn = ["install"]
cmds = ["npm run build --prefix ksl-web"]

[start]
cmd = "uvicorn main:app --host 0.0.0.0 --port ${PORT:-8000}"
