[phases.setup]
nixPkgs = ["nodejs_20", "python311"]

[phases.install]
cmds = [
    "pip install -r requirements.txt",
    "cd ksl-web && npm install"
]

[phases.build]
cmds = [
    "cd ksl-web && npm run build"
]

[start]
cmd = "uvicorn main:app --host 0.0.0.0 --port ${PORT:-8000}"
